import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#e0f7fa', // Un color de fondo más suave
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#263238',
    marginBottom: 30,
  },
  stressNotification: {
    backgroundColor: '#ef5350',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 10,
    marginBottom: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  stressNotificationText: {
    color: '#ffffff',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 16,
  },
  userDataContainer: {
    marginBottom: 35,
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#ffffff',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.20,
    shadowRadius: 1.41,
    elevation: 2,
  },
  userDataText: {
    fontSize: 17,
    color: '#455a64',
    marginBottom: 7,
  },
  breathingContainer: {
    width: 250,
    height: 250,
    borderRadius: 125,
    backgroundColor: 'rgba(100, 181, 246, 0.3)', // Azul claro semitransparente
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 60,
    borderWidth: 2,
    borderColor: '#2196f3',
    overflow: 'hidden',
  },
  breathingCircle: {
    width: '100%',
    height: '100%',
    borderRadius: 125,
    backgroundColor: '#2196f3', // Azul vibrante
    position: 'absolute',
  },
  instructionText: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#ffffff',
    zIndex: 1, // Asegura que el texto esté sobre el círculo
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  controls: {
    flexDirection: 'row',
    marginTop: 20,
  },
  button: {
    backgroundColor: '#4caf50', // Verde para iniciar/detener
    paddingVertical: 14,
    paddingHorizontal: 35,
    borderRadius: 30,
    marginHorizontal: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  buttonText: {
    color: '#ffffff',
    fontSize: 19,
    fontWeight: 'bold',
  },
  suggestionButtonsContainer: {
    flexDirection: 'row',
    marginTop: 15,
  },
  acceptButton: {
    backgroundColor: '#4caf50',
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 25,
    marginHorizontal: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  declineButton: {
    backgroundColor: '#f44336',
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 25,
    marginHorizontal: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  timerText: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#3f51b5',
    marginTop: 20,
  },
  progressBarContainer: {
    width: '80%',
    height: 10,
    backgroundColor: '#e0e0e0',
    borderRadius: 5,
    marginTop: 20,
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    backgroundColor: '#4caf50',
    borderRadius: 5,
  },
});